# FriendlyChat Codelab

use_frameworks!
platform :ios, '7.0'

pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Invites'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'

target 'FriendlyChatSwift' do
end
