# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target ‘ChatChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireChat
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
  pod 'Firebase/Crash'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod ‘Google/SignIn’
  pod 'Firebase/DynamicLinks'  
  pod 'Firebase/Storage'
  pod 'Firebase/Invites'
  pod 'Firebase/RemoteConfig'
  pod 'SDWebImage'

end
